name: tests
on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: PHPUnit
              uses: tf-tech/actions-phpunit-symfony@master
